"""Database layer for Field Intelligence Platform.

SQLite is used locally; PostgreSQL is used in Render when DATABASE_URL is set.
The demo seed contains synthetic data only.  The schema separates permanent
properties, reusable contacts, visits, ownership/status, and audit history.
"""
import os, re, sqlite3
from datetime import datetime
import pandas as pd

DATABASE_URL=os.environ.get('DATABASE_URL','').strip()
IS_PG=DATABASE_URL.startswith(('postgres://','postgresql://'))
SQLITE_PATH=os.environ.get('FIELD_DB','field_intel.db')
HERE=os.path.dirname(os.path.abspath(__file__))
CSV_NAME=os.environ.get('SEED_CSV','synthetic_field_visits_110_records.csv')
CSV_PATH=os.path.join(HERE,'data',CSV_NAME)
if not os.path.exists(CSV_PATH): CSV_PATH=os.path.join(HERE,CSV_NAME)
SEED_VERSION=os.environ.get('SEED_VERSION','2026-08-22-v3')
DEMO_MODE=os.environ.get('DEMO_MODE','true').lower() in ('1','true','yes')
_PK='BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY' if IS_PG else 'INTEGER PRIMARY KEY AUTOINCREMENT'
_NOW='NOW()' if IS_PG else 'CURRENT_TIMESTAMP'

SCHEMA=f"""
CREATE TABLE IF NOT EXISTS properties (
 property_id {_PK}, property_name TEXT NOT NULL, brand TEXT DEFAULT '', branch TEXT DEFAULT '',
 parent_site TEXT DEFAULT '', area TEXT DEFAULT '', territory TEXT DEFAULT '', property_type TEXT DEFAULT '',
 latitude DOUBLE PRECISION, longitude DOUBLE PRECISION, coord_source TEXT DEFAULT '',
 location_confidence TEXT DEFAULT '', exact_location TEXT DEFAULT '', created_by TEXT DEFAULT '',
 current_status TEXT DEFAULT 'Open', owner_rep TEXT DEFAULT '', last_outcome TEXT DEFAULT '',
 last_visited_at TEXT DEFAULT '', created_at TIMESTAMP DEFAULT {_NOW}
);
CREATE TABLE IF NOT EXISTS contacts (
 contact_id {_PK}, property_id BIGINT NOT NULL, name TEXT DEFAULT '', designation TEXT DEFAULT '',
 email TEXT DEFAULT '', phone TEXT DEFAULT '', contact_type TEXT DEFAULT '', source TEXT DEFAULT '',
 verified INTEGER DEFAULT 0, notes TEXT DEFAULT '', created_at TIMESTAMP DEFAULT {_NOW}, updated_at TIMESTAMP DEFAULT {_NOW}
);
CREATE TABLE IF NOT EXISTS visits (
 visit_id {_PK}, property_id BIGINT NOT NULL, rep TEXT NOT NULL, visit_date TEXT DEFAULT '', visit_month TEXT DEFAULT '',
 date_precision TEXT DEFAULT '', record_type TEXT DEFAULT 'prospect_visit', outcome_category TEXT DEFAULT '',
 access_blocked INTEGER DEFAULT 0, follow_up_state TEXT DEFAULT '', requirement_detail TEXT DEFAULT '',
 competitor_vendor TEXT DEFAULT '', pricing_note TEXT DEFAULT '', contact_role TEXT DEFAULT '',
 contact_id BIGINT, contact_name TEXT DEFAULT '', contact_email TEXT DEFAULT '', contact_phone TEXT DEFAULT '',
 contact_designation TEXT DEFAULT '', exact_location TEXT DEFAULT '', remarks TEXT DEFAULT '', source TEXT DEFAULT '',
 logged_lat DOUBLE PRECISION, logged_lon DOUBLE PRECISION, overlap_flag INTEGER DEFAULT 0, overlap_rep TEXT DEFAULT '',
 created_at TIMESTAMP DEFAULT {_NOW}
);
CREATE TABLE IF NOT EXISTS audit (
 audit_id {_PK}, at TIMESTAMP DEFAULT {_NOW}, actor TEXT DEFAULT '', action TEXT DEFAULT '', entity TEXT DEFAULT '',
 entity_id BIGINT, detail TEXT DEFAULT ''
);
CREATE TABLE IF NOT EXISTS meta (key TEXT PRIMARY KEY, value TEXT DEFAULT '');
CREATE INDEX IF NOT EXISTS ix_visits_property ON visits(property_id);
CREATE INDEX IF NOT EXISTS ix_visits_rep ON visits(rep);
CREATE INDEX IF NOT EXISTS ix_props_coords ON properties(latitude,longitude);
CREATE INDEX IF NOT EXISTS ix_contacts_property ON contacts(property_id);
"""

class Conn:
 def __init__(self,raw,is_pg): self.raw,self.is_pg=raw,is_pg
 def _sql(self,sql): return re.sub(r'\?', '%s', sql) if self.is_pg else sql
 def execute(self,sql,args=()):
  cur=self.raw.cursor()
  try: cur.execute(self._sql(sql),args)
  except Exception:
   if self.is_pg:
    try:self.raw.rollback()
    except Exception:pass
   raise
  return _Cursor(cur,self.is_pg)
 def executescript(self,script):
  if self.is_pg:
   cur=self.raw.cursor(); cur.execute(script); self.raw.commit()
  else:self.raw.executescript(script)
 def insert(self,sql,args=(),pk='id'):
  cur=self.raw.cursor()
  try:
   if self.is_pg:
    cur.execute(self._sql(sql)+f' RETURNING {pk}',args); return cur.fetchone()[0]
   cur.execute(sql,args); return cur.lastrowid
  except Exception:
   if self.is_pg:
    try:self.raw.rollback()
    except Exception:pass
   raise
 def commit(self): self.raw.commit()
 def rollback(self): self.raw.rollback()
class _Cursor:
 def __init__(self,cur,is_pg): self.cur,self.is_pg=cur,is_pg
 def _row(self,r):
  if r is None:return None
  if self.is_pg:return dict(zip([d[0] for d in self.cur.description],r))
  return r
 def fetchone(self):return self._row(self.cur.fetchone())
 def fetchall(self):return [self._row(r) for r in self.cur.fetchall()]
 def __iter__(self):return iter(self.fetchall())

def _add_column(con, table, col, typ, default_sql=None):
 try:
  con.execute(f'ALTER TABLE {table} ADD COLUMN {col} {typ}' + (f' DEFAULT {default_sql}' if default_sql else ''))
  con.commit()
 except Exception as e:
  msg=str(e).lower()
  if 'duplicate column' not in msg and 'already exists' not in msg: raise

def _migrate(con):
 # Existing Render databases from older builds are upgraded in place.
 existing={r['name'] for r in con.execute("SELECT name FROM pragma_table_info('properties')").fetchall()} if not IS_PG else {r['column_name'] for r in con.execute("SELECT column_name FROM information_schema.columns WHERE table_name='properties'").fetchall()}
 for c,t,d in [('exact_location','TEXT',"''"),('current_status','TEXT',"'Open'"),('owner_rep','TEXT',"''"),('last_outcome','TEXT',"''"),('last_visited_at','TEXT',"''")]:
  if c not in existing:_add_column(con,'properties',c,t,d)
 existing={r['name'] for r in con.execute("SELECT name FROM pragma_table_info('visits')").fetchall()} if not IS_PG else {r['column_name'] for r in con.execute("SELECT column_name FROM information_schema.columns WHERE table_name='visits'").fetchall()}
 for c,t,d in [('contact_id','BIGINT',None),('contact_name','TEXT',"''"),('contact_email','TEXT',"''"),('contact_phone','TEXT',"''"),('contact_designation','TEXT',"''"),('exact_location','TEXT',"''"),('overlap_flag','INTEGER','0'),('overlap_rep','TEXT',"''")]:
  if c not in existing:_add_column(con,'visits',c,t,d)
 con.commit()

def connect(url=None):
 url=DATABASE_URL if url is None else url
 if url.startswith(('postgres://','postgresql://')):
  import psycopg
  raw=psycopg.connect(url,autocommit=False); con=Conn(raw,True)
 else:
  raw=sqlite3.connect(url or SQLITE_PATH,check_same_thread=False); raw.row_factory=sqlite3.Row; raw.execute('PRAGMA foreign_keys=ON'); con=Conn(raw,False)
 try:
  con.executescript(SCHEMA); _migrate(con); con.commit(); return con
 except Exception:
  con.rollback(); raw.close(); raise

def backend():return 'postgres' if IS_PG else 'sqlite'
def _s(v):
 if v is None or (isinstance(v,float) and pd.isna(v)):return ''
 return str(v).strip()
def _f(v):
 try:
  if v is None or _s(v)=='':return None
  x=float(v); return x if pd.notna(x) else None
 except:return None

def log_audit(con,actor,action,entity,entity_id=None,detail=''):
 con.execute('INSERT INTO audit(actor,action,entity,entity_id,detail) VALUES(?,?,?,?,?)',(actor,action,entity,entity_id,detail)); con.commit()

def _status_from_visits(visits):
 if not visits:return 'Open',''
 # Most recent business outcome controls current ownership/state.
 ordered=sorted(visits,key=lambda v:(v.get('visit_date') or '',v.get('created_at') or ''))
 for v in reversed(ordered):
  out=_s(v.get('outcome_category'))
  if out in ('SPACE_SHORTAGE','DEMAND_CAPACITY_MISMATCH','OPERATIONAL_INEFFICIENCY','FUTURE_OPPORTUNITY','SITE_AVAILABLE','ACCOUNT_AT_RISK','FOLLOW_UP_PENDING'):
   return ('Follow-up' if out=='FOLLOW_UP_PENDING' else 'Opportunity'), _s(v.get('rep'))
  if out=='NO_REQUIREMENT':return 'No Requirement',''
  if out=='NOT_INTERESTED':return 'Not Interested',''
  if out=='COMPETITOR_LOCKED':return 'Competitor',''
  if out=='UNQUALIFIED':return 'Access Blocked',''
 return 'Checked',''

def refresh_property_state(con,property_id):
 rows=[dict(r) for r in con.execute('SELECT * FROM visits WHERE property_id=? ORDER BY visit_date,visit_id',(property_id,)).fetchall()]
 status,owner=_status_from_visits(rows)
 last=rows[-1] if rows else None
 con.execute('UPDATE properties SET current_status=?, owner_rep=?, last_outcome=?, last_visited_at=? WHERE property_id=?',(status,owner,_s(last['outcome_category']) if last else '',_s(last['visit_date']) if last else '',property_id)); con.commit()
 return status,owner

def _normalize(df):
 rename={
 'PROPERTY NAME':'property_name','BRAND':'brand','BRANCH':'branch','PARENT SITE':'parent_site','AREA':'area','REGION':'territory','TYPE':'property_type',
 'FULL ADDRESS':'full_address','EXACT LOCATION':'exact_location','LAT':'latitude','LON':'longitude','SOURCE':'source_doc','LOCATION CONFIDENCE':'location_confidence',
 'REP':'rep','VISIT DATE':'visit_date','OUTCOME':'outcome_category','REQUIREMENT':'requirement_detail','COMPETITOR/VENDOR':'competitor_vendor','PRICING':'pricing_note',
 'CONTACT ROLE':'contact_role_obtained','CONTACT NAME':'contact_name','CONTACT EMAIL':'contact_email','CONTACT PHONE':'contact_phone','FOLLOW-UP':'follow_up_state',
 'REMARKS':'remarks','LOGGED_LAT':'logged_lat','LOGGED_LON':'logged_lon','OVERLAP_FLAG':'overlap_flag','OVERLAP_REP':'overlap_rep','OWNER_REP':'owner_rep','PROPERTY_STATUS':'property_status'}
 df=df.rename(columns={k:v for k,v in rename.items() if k in df.columns}).fillna('')
 defaults={'property_name':'','brand':'','branch':'','parent_site':'','area':'','territory':'','property_type':'commercial','latitude':'','longitude':'','exact_location':'','location_confidence':'',
 'rep':'','visit_date':'','outcome_category':'','requirement_detail':'','competitor_vendor':'','pricing_note':'','contact_role_obtained':'','contact_name':'','contact_email':'','contact_phone':'','follow_up_state':'none','remarks':'','source_doc':'synthetic_demo','logged_lat':'','logged_lon':'','overlap_flag':'','overlap_rep':'','owner_rep':'','property_status':''}
 for c,d in defaults.items():
  if c not in df:df[c]=d
 outcome={'Opportunity':'SPACE_SHORTAGE','No Requirement':'NO_REQUIREMENT','Follow-up':'FOLLOW_UP_PENDING','Not Interested':'NOT_INTERESTED','Competitor':'COMPETITOR_LOCKED','Access Blocked':'UNQUALIFIED','Space Shortage':'SPACE_SHORTAGE','Operational Inefficiency':'OPERATIONAL_INEFFICIENCY','Potential Overlap':'OVERLAP_REVIEW','Could Not Reach Decision Maker':'UNQUALIFIED'}
 df['outcome_category']=df['outcome_category'].apply(lambda x:outcome.get(_s(x),_s(x)))
 follow={'':'none','none':'none','proposal_requested':'proposal_requested','quote_requested':'quote_requested','follow_up_scheduled':'follow_up_scheduled','awaiting_callback':'awaiting_callback','proposal_pending':'proposal_pending','revisit_needed':'revisit_needed','email_follow_up':'email_follow_up','contact_obtained':'contact_obtained'}
 df['follow_up_state']=df['follow_up_state'].apply(lambda x:follow.get(_s(x),_s(x) or 'none'))
 return df

def load_csv(con,csv_path=None,reset=True):
 df=_normalize(pd.read_csv(csv_path or CSV_PATH))
 if reset:
  con.execute('DELETE FROM visits'); con.execute('DELETE FROM contacts'); con.execute('DELETE FROM properties'); con.commit()
 prop_ids={}
 for _,r in df.iterrows():
  key=(_s(r.property_name),_s(r.parent_site),_s(r.area))
  if key in prop_ids:continue
  pid=con.insert('''INSERT INTO properties(property_name,brand,branch,parent_site,area,territory,property_type,latitude,longitude,coord_source,location_confidence,exact_location,created_by,current_status,owner_rep,last_outcome,last_visited_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)''',
   (key[0],_s(r.brand),_s(r.branch),key[1],key[2],_s(r.territory),_s(r.property_type),_f(r.latitude),_f(r.longitude),'seed',_s(r.location_confidence),_s(r.exact_location),'seed','Open','', '', ''),pk='property_id')
  prop_ids[key]=pid
  # one reusable synthetic contact per property; visit rows can still point to it.
  cid=con.insert('INSERT INTO contacts(property_id,name,designation,email,phone,contact_type,source,verified) VALUES(?,?,?,?,?,?,?,?)',
    (pid,_s(r.contact_name),_s(r.contact_role_obtained),_s(r.contact_email),_s(r.contact_phone),_s(r.contact_role_obtained),'synthetic_demo',1),pk='contact_id')
  # keep contact id in a temporary map
  prop_ids[(key,'contact')]=cid
 for _,r in df.iterrows():
  key=(_s(r.property_name),_s(r.parent_site),_s(r.area)); pid=prop_ids[key]; cid=prop_ids[(key,'contact')]
  con.execute('''INSERT INTO visits(property_id,rep,visit_date,visit_month,date_precision,record_type,outcome_category,access_blocked,follow_up_state,requirement_detail,competitor_vendor,pricing_note,contact_role,contact_id,contact_name,contact_email,contact_phone,contact_designation,exact_location,remarks,source,logged_lat,logged_lon,overlap_flag,overlap_rep) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)''',
   (pid,_s(r.rep),_s(r.visit_date),_s(r.visit_date)[:7],'exact','prospect_visit',_s(r.outcome_category),1 if _s(r.outcome_category)=='UNQUALIFIED' and _s(r.get('outcome_category'))=='UNQUALIFIED' else 0,_s(r.follow_up_state),_s(r.requirement_detail),_s(r.competitor_vendor),_s(r.pricing_note),_s(r.contact_role_obtained),cid,_s(r.contact_name),_s(r.contact_email),_s(r.contact_phone),_s(r.contact_role_obtained),_s(r.exact_location),_s(r.remarks),_s(r.source_doc),_f(r.logged_lat),_f(r.logged_lon),1 if _s(r.overlap_flag).lower()=='yes' else 0,_s(r.overlap_rep)))
 con.commit()
 for pid in set(prop_ids.values()):
  if isinstance(pid,int):refresh_property_state(con,pid)
 con.execute('INSERT INTO meta(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=?',( 'seed_version',SEED_VERSION,SEED_VERSION)); con.commit()
 log_audit(con,'system','seed','database',None,f'{len(prop_ids)//2} properties, {len(df)} visits, seed={SEED_VERSION}')
 return con.execute('SELECT COUNT(*) c FROM properties').fetchone()['c'],con.execute('SELECT COUNT(*) c FROM visits').fetchone()['c']

def ensure_seeded(con):
 p=con.execute('SELECT COUNT(*) c FROM properties').fetchone()['c']; v=con.execute('SELECT COUNT(*) c FROM visits').fetchone()['c']
 app_entries=con.execute("SELECT COUNT(*) c FROM visits WHERE source='app_entry'").fetchone()['c']
 old_demo=(DEMO_MODE and p<70 and app_entries==0)
 seedver=con.execute("SELECT value FROM meta WHERE key='seed_version'").fetchone()
 if p==0 or old_demo or not seedver:
  return load_csv(con,reset=True)
 return p,v

def stats(con):
 return {'backend':backend(),'properties':con.execute('SELECT COUNT(*) c FROM properties').fetchone()['c'],'visits':con.execute('SELECT COUNT(*) c FROM visits').fetchone()['c'],'contacts':con.execute('SELECT COUNT(*) c FROM contacts').fetchone()['c'],'geocoded':con.execute('SELECT COUNT(*) c FROM properties WHERE latitude IS NOT NULL').fetchone()['c'],'logged_in_app':con.execute("SELECT COUNT(*) c FROM visits WHERE source='app_entry'").fetchone()['c'],'reps':[dict(r) for r in con.execute('SELECT rep,COUNT(*) n FROM visits GROUP BY rep ORDER BY n DESC').fetchall()]}

def export_frame(con):
 rows=con.execute('''SELECT p.property_name,p.brand,p.branch,p.area,p.territory,p.property_type,p.parent_site,p.exact_location,p.latitude,p.longitude,p.current_status,p.owner_rep,c.name contact_name,c.designation contact_role,c.email contact_email,c.phone contact_phone,v.rep,v.visit_date,v.outcome_category,v.requirement_detail,v.follow_up_state,v.remarks,v.overlap_flag,v.overlap_rep,v.logged_lat,v.logged_lon,v.created_at FROM visits v JOIN properties p ON p.property_id=v.property_id LEFT JOIN contacts c ON c.contact_id=v.contact_id ORDER BY v.created_at''').fetchall()
 return pd.DataFrame([dict(r) for r in rows])

if __name__=='__main__':
 c=connect(); print('backend:',backend()); print(ensure_seeded(c)); print(stats(c))
