"""
db.py — the database layer.

Runs on SQLite locally and Postgres in production, chosen by one environment
variable:

    DATABASE_URL unset            -> SQLite file (fast, zero setup, ephemeral)
    DATABASE_URL=postgresql://…   -> Postgres (survives restarts, multi-user)

That matters because a container's local disk is wiped on every rebuild. A
rep logging a visit from the field needs it to still be there next week, and
needs the other three reps to see it immediately. A file on ephemeral disk
cannot do that; a hosted Postgres can.

The two dialects differ in three small ways, handled here so nothing else in
the codebase has to care:

    placeholders   SQLite uses ?, Postgres uses %s
    autoincrement  INTEGER PRIMARY KEY vs GENERATED … AS IDENTITY
    returning ids  lastrowid vs RETURNING

Tables
    properties  one row per real-world location
    visits      one row per visit, pointing at a property
    audit       append-only record of every write, so the history of the
                history is recoverable
"""

import os
import re
import sqlite3
from datetime import datetime, timezone

import pandas as pd

DATABASE_URL = os.environ.get("DATABASE_URL", "").strip()
IS_PG = DATABASE_URL.startswith(("postgres://", "postgresql://"))

SQLITE_PATH = os.environ.get("FIELD_DB", "field_intel.db")
HERE = os.path.dirname(os.path.abspath(__file__))
CSV_PATH = os.path.join(HERE, "data", os.environ.get("SEED_CSV", "synthetic_field_visits_110_records.csv"))
if not os.path.exists(CSV_PATH):
    CSV_PATH = os.path.join(HERE, os.environ.get("SEED_CSV", "synthetic_field_visits_110_records.csv"))

# --------------------------------------------------------------- schema
_PK = ("BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if IS_PG
       else "INTEGER PRIMARY KEY AUTOINCREMENT")
_NOW = "NOW()" if IS_PG else "CURRENT_TIMESTAMP"

SCHEMA = f"""
CREATE TABLE IF NOT EXISTS properties (
    property_id         {_PK},
    property_name       TEXT NOT NULL,
    brand               TEXT DEFAULT '',
    branch              TEXT DEFAULT '',
    parent_site         TEXT DEFAULT '',
    area                TEXT DEFAULT '',
    territory           TEXT DEFAULT '',
    property_type       TEXT DEFAULT '',
    latitude            DOUBLE PRECISION,
    longitude           DOUBLE PRECISION,
    coord_source        TEXT DEFAULT '',
    location_confidence TEXT DEFAULT '',
    created_by          TEXT DEFAULT '',
    created_at          TIMESTAMP DEFAULT {_NOW}
);

CREATE TABLE IF NOT EXISTS visits (
    visit_id           {_PK},
    property_id        BIGINT NOT NULL,
    rep                TEXT NOT NULL,
    visit_date         TEXT DEFAULT '',
    visit_month        TEXT DEFAULT '',
    date_precision     TEXT DEFAULT '',
    record_type        TEXT DEFAULT 'prospect_visit',
    outcome_category   TEXT DEFAULT '',
    access_blocked     INTEGER DEFAULT 0,
    follow_up_state    TEXT DEFAULT '',
    requirement_detail TEXT DEFAULT '',
    competitor_vendor  TEXT DEFAULT '',
    pricing_note       TEXT DEFAULT '',
    contact_role       TEXT DEFAULT '',
    remarks            TEXT DEFAULT '',
    source             TEXT DEFAULT '',
    logged_lat         DOUBLE PRECISION,
    logged_lon         DOUBLE PRECISION,
    created_at         TIMESTAMP DEFAULT {_NOW}
);

CREATE TABLE IF NOT EXISTS audit (
    audit_id   {_PK},
    at         TIMESTAMP DEFAULT {_NOW},
    actor      TEXT DEFAULT '',
    action     TEXT DEFAULT '',
    entity     TEXT DEFAULT '',
    entity_id  BIGINT,
    detail     TEXT DEFAULT ''
);

CREATE INDEX IF NOT EXISTS ix_visits_property ON visits(property_id);
CREATE INDEX IF NOT EXISTS ix_visits_rep      ON visits(rep);
CREATE INDEX IF NOT EXISTS ix_visits_created  ON visits(created_at);
CREATE INDEX IF NOT EXISTS ix_props_coords    ON properties(latitude, longitude);
"""


# ----------------------------------------------------------- connection
class Conn:
    """Thin wrapper so callers write one SQL dialect.

    Everything else in the codebase calls con.execute("… WHERE id = ?", (x,))
    and gets dict-like rows back, whichever backend is in use.
    """

    def __init__(self, raw, is_pg):
        self.raw = raw
        self.is_pg = is_pg

    def _sql(self, sql):
        return re.sub(r"\?", "%s", sql) if self.is_pg else sql

    def execute(self, sql, args=()):
        cur = self.raw.cursor()
        cur.execute(self._sql(sql), args)
        return _Cursor(cur, self.is_pg)

    def executescript(self, script):
        if self.is_pg:
            cur = self.raw.cursor()
            cur.execute(script)
            self.raw.commit()
        else:
            self.raw.executescript(script)

    def insert(self, sql, args=(), pk="id"):
        """INSERT that returns the new primary key on both backends."""
        cur = self.raw.cursor()
        if self.is_pg:
            cur.execute(self._sql(sql) + f" RETURNING {pk}", args)
            return cur.fetchone()[0]
        cur.execute(sql, args)
        return cur.lastrowid

    def commit(self):
        self.raw.commit()

    def rollback(self):
        self.raw.rollback()


class _Cursor:
    def __init__(self, cur, is_pg):
        self.cur = cur
        self.is_pg = is_pg
        self.lastrowid = None if is_pg else cur.lastrowid

    def _row(self, r):
        if r is None:
            return None
        if self.is_pg:
            cols = [d[0] for d in self.cur.description]
            return dict(zip(cols, r))
        return r

    def fetchone(self):
        return self._row(self.cur.fetchone())

    def fetchall(self):
        return [self._row(r) for r in self.cur.fetchall()]

    def __iter__(self):
        return iter(self.fetchall())


def connect(url=None):
    """Open a connection and make sure the schema exists."""
    url = url if url is not None else DATABASE_URL
    if url.startswith(("postgres://", "postgresql://")):
        import psycopg
        raw = psycopg.connect(url, autocommit=False)
        con = Conn(raw, True)
    else:
        raw = sqlite3.connect(url or SQLITE_PATH, check_same_thread=False)
        raw.row_factory = sqlite3.Row
        raw.execute("PRAGMA foreign_keys = ON")
        con = Conn(raw, False)
    con.executescript(SCHEMA)
    con.commit()
    return con


def backend():
    return "postgres" if IS_PG else "sqlite"


# ------------------------------------------------------------- helpers
def _s(v):
    if v is None or (isinstance(v, float) and pd.isna(v)):
        return ""
    return str(v).strip()


def _f(v):
    try:
        if v is None or (isinstance(v, float) and pd.isna(v)) or _s(v) == "":
            return None
        return float(v)
    except Exception:
        return None


def log_audit(con, actor, action, entity, entity_id=None, detail=""):
    """Append-only trail. Nothing is ever deleted from this table, so if a
    record is later edited or a merge turns out wrong, the original is still
    recoverable."""
    con.execute(
        "INSERT INTO audit (actor, action, entity, entity_id, detail) "
        "VALUES (?,?,?,?,?)",
        (actor, action, entity, entity_id, detail))
    con.commit()


# ---------------------------------------------------------------- seed
def load_csv(con, csv_path=None, reset=True):
    """Load seed field reports. Accepts the V2 synthetic dataset schema and
    also tolerates the older internal CSV column names. Runs only when the
    target database is empty, so production data is never replaced by a seed.
    """
    df = pd.read_csv(csv_path or CSV_PATH).fillna("")

    # Normalize the public/demo CSV into the internal database vocabulary.
    # This keeps the database layer stable even if the exported dataset uses
    # human-readable column names.
    rename_map = {
        "PROPERTY NAME": "property_name", "BRAND": "brand", "BRANCH": "branch",
        "PARENT SITE": "parent_site", "AREA": "area", "REGION": "territory",
        "TYPE": "property_type", "FULL ADDRESS": "full_address",
        "LAT": "latitude", "LON": "longitude", "SOURCE": "source_doc",
        "LOCATION CONFIDENCE": "location_confidence", "REP": "rep",
        "VISIT DATE": "visit_date", "OUTCOME": "outcome_category",
        "REQUIREMENT": "requirement_detail", "COMPETITOR/VENDOR": "competitor_vendor",
        "PRICING": "pricing_note", "CONTACT ROLE": "contact_role_obtained",
        "FOLLOW-UP": "follow_up_state", "REMARKS": "remarks",
        "LOGGED_LAT": "logged_lat", "LOGGED_LON": "logged_lon",
    }
    df = df.rename(columns={k: v for k, v in rename_map.items() if k in df.columns})

    # Fill fields that older exports may not contain.
    defaults = {
        "property_name": "", "brand": "", "branch": "", "parent_site": "",
        "area": "", "territory": "", "property_type": "commercial",
        "latitude": "", "longitude": "", "coord_source": "seed",
        "location_confidence": "", "rep": "", "visit_date": "",
        "visit_month": "", "date_precision": "day", "record_type": "prospect_visit",
        "outcome_category": "", "access_blocked": 0, "follow_up_state": "none",
        "requirement_detail": "", "competitor_vendor": "", "pricing_note": "",
        "contact_role_obtained": "", "remarks": "", "source_doc": "synthetic_demo",
        "logged_lat": "", "logged_lon": "",
    }
    for col, default in defaults.items():
        if col not in df.columns:
            df[col] = default

    # Human-readable demo outcome labels -> controlled outcome codes.
    outcome_map = {
        "Opportunity": "SPACE_SHORTAGE",
        "No Requirement": "NO_REQUIREMENT",
        "Follow-up": "FOLLOW_UP_PENDING",
        "Competitor": "COMPETITOR_LOCKED",
        "Access Blocked": "UNQUALIFIED",
        "Space Shortage": "SPACE_SHORTAGE",
        "Operational Inefficiency": "OPERATIONAL_INEFFICIENCY",
    }
    df["outcome_category"] = df["outcome_category"].apply(lambda x: outcome_map.get(_s(x), _s(x)))
    follow_map = {
        "": "none", "Share proposal": "proposal_requested",
        "Call facility manager": "contact_obtained", "Revisit next week": "revisit_needed",
        "Send quotation": "quote_requested", "Check requirement next month": "monitor",
    }
    df["follow_up_state"] = df["follow_up_state"].apply(lambda x: follow_map.get(_s(x), _s(x) or "none"))
    df["access_blocked"] = df.apply(lambda r: 1 if _s(r.get("outcome_category")) == "UNQUALIFIED" else int(r.get("access_blocked") or 0), axis=1)
    df["coord_source"] = df["coord_source"].apply(lambda x: _s(x) or "seed")
    # Use the public full address as the property location label when parent_site
    # is blank.
    df["parent_site"] = df.apply(lambda r: _s(r.get("parent_site")) or _s(r.get("full_address")), axis=1)

    if reset:
        con.execute("DELETE FROM visits")
        con.execute("DELETE FROM properties")
        con.commit()

    prop_ids = {}
    for _, r in df.iterrows():
        key = (_s(r.property_name), _s(r.parent_site), _s(r.area))
        if key in prop_ids:
            continue
        pid = con.insert(
            """INSERT INTO properties
               (property_name, brand, branch, parent_site, area, territory,
                property_type, latitude, longitude, coord_source,
                location_confidence, created_by)
               VALUES (?,?,?,?,?,?,?,?,?,?,?,?)""",
            (key[0], _s(r.get("brand")), _s(r.get("branch")), key[1], key[2],
             _s(r.territory), _s(r.property_type), _f(r.latitude), _f(r.longitude),
             _s(r.coord_source), _s(r.get("location_confidence")), "seed"),
            pk="property_id")
        prop_ids[key] = pid

    for _, r in df.iterrows():
        key = (_s(r.property_name), _s(r.parent_site), _s(r.area))
        con.execute(
            """INSERT INTO visits
               (property_id, rep, visit_date, visit_month, date_precision,
                record_type, outcome_category, access_blocked, follow_up_state,
                requirement_detail, competitor_vendor, pricing_note,
                contact_role, remarks, source)
               VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)""",
            (prop_ids[key], _s(r.rep), _s(r.visit_date), _s(r.get("visit_month")),
             _s(r.get("date_precision")), _s(r.record_type), _s(r.outcome_category),
             int(r.get("access_blocked") or 0), _s(r.follow_up_state),
             _s(r.requirement_detail), _s(r.competitor_vendor), _s(r.pricing_note),
             _s(r.contact_role_obtained), _s(r.remarks), _s(r.source_doc)))

    con.commit()
    log_audit(con, "system", "seed", "database", None,
              f"{len(prop_ids)} properties, {len(df)} visits")
    p = con.execute("SELECT COUNT(*) c FROM properties").fetchone()["c"]
    v = con.execute("SELECT COUNT(*) c FROM visits").fetchone()["c"]
    return p, v


def ensure_seeded(con):
    """Seed only if empty. Safe to call on every start."""
    n = con.execute("SELECT COUNT(*) c FROM properties").fetchone()["c"]
    if n == 0:
        return load_csv(con, reset=False)
    return n, con.execute("SELECT COUNT(*) c FROM visits").fetchone()["c"]


def stats(con):
    q = lambda s: con.execute(s).fetchall()
    return {
        "backend": backend(),
        "properties": q("SELECT COUNT(*) c FROM properties")[0]["c"],
        "visits": q("SELECT COUNT(*) c FROM visits")[0]["c"],
        "geocoded": q("SELECT COUNT(*) c FROM properties "
                      "WHERE latitude IS NOT NULL")[0]["c"],
        "logged_in_app": q("SELECT COUNT(*) c FROM visits "
                           "WHERE source = 'app_entry'")[0]["c"],
        "reps": [dict(r) for r in q(
            "SELECT rep, COUNT(*) n FROM visits GROUP BY rep ORDER BY n DESC")],
    }


def export_frame(con):
    """Everything, flat, for backup or handover."""
    rows = con.execute("""
        SELECT p.property_name, p.brand, p.area, p.territory, p.property_type,
               p.latitude, p.longitude, p.coord_source, p.location_confidence,
               v.rep, v.visit_date, v.visit_month, v.record_type,
               v.outcome_category, v.access_blocked, v.follow_up_state,
               v.requirement_detail, v.competitor_vendor, v.pricing_note,
               v.contact_role, v.remarks, v.source, v.logged_lat, v.logged_lon,
               v.created_at
        FROM visits v JOIN properties p ON p.property_id = v.property_id
        ORDER BY v.created_at""").fetchall()
    return pd.DataFrame([dict(r) for r in rows])


if __name__ == "__main__":
    c = connect()
    print("backend:", backend())
    print(ensure_seeded(c))
    from pprint import pprint
    pprint(stats(c))
